### ISSUE TITLE
Issue with ID using example call

### ISSUE THREAD

**Issue by Jaker86** [dmitriy-serdyuk/arxiv2kindle#2]
Just installed using pip install arxiv2kindle

(base) jake@JakesMacbookBro ~ % arxiv2kindle --width 6 --height 4 --margin 0.2 --landscape "Towards end-to-end spoken language understanding" ./
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
pdftk port to java 3.3.3 a Handy Tool for Manipulating PDF Documents
Copyright (c) 2017-2018 Marc Vinyals - https://gitlab.com/pdftk-java/pdftk
Copyright (c) 2003-2013 Steward and Lee, LLC.
pdftk includes a modified version of the iText library.
Copyright (c) 1999-2009 Bruno Lowagie, Paulo Soares, et al.
This is free software; see the source code for copying conditions. There is
NO warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Traceback (most recent call last):
  File "/Users/jake/opt/anaconda3/bin/arxiv2kindle", line 8, in <module>
    sys.exit(run())
  File "/Users/jake/opt/anaconda3/lib/python3.9/site-packages/arxiv2kindle.py", line 237, in run
    main(**vars(parse_args()))
  File "/Users/jake/opt/anaconda3/lib/python3.9/site-packages/arxiv2kindle.py", line 212, in main
    tmp_dir, main_file, title = download(query)
  File "/Users/jake/opt/anaconda3/lib/python3.9/site-packages/arxiv2kindle.py", line 61, in download
    arxiv_id = paper['id']
  File "/Users/jake/opt/anaconda3/lib/python3.9/site-packages/feedparser/util.py", line 113, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'id'

**Comment by EnriqueSampaio** [comment]
What I did to fix it was to go to the arxiv2kindle.py file (in your case located at /Users/jake/opt/anaconda3/lib/python3.9/site-packages/arxiv2kindle.py) and replace the line 61 with the following:

`arxiv_url = paper['arxiv_url']`

And at the line 64 changed the content to:

`logger.info(f"Converting paper: [{arxiv_url}] {arxiv_title}")`

Just like the last commit at master branch: https://github.com/dmitriy-serdyuk/arxiv2kindle/commit/7a21743c7966cad3143eb71024db6a434e4c3019
